#!/usr/bin/groovy


    		envList = "Oracle12c\nOracle19c"

pipeline {
	agent any
	

	 parameters {
        	choice(choices: "${envList}", name: 'OracleVersion', description: 'please choose the Oracle version you want to deploy?')
   
   	 }

	
	stages {

		stage('Build') {
			steps {
				echo "Building..${params.OracleVersion}"
			}
		}

		stage('Test') {
			steps {
				echo 'Testing..'
			}
		}

		stage('Deploy') {
			steps {
				echo 'Deploying....'
			}
		}

	}
}
